// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgoxzvcbfzpnrdplyjti.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indnb3h6dmNiZnpwbnJkcGx5anRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMzU5MjUsImV4cCI6MjA2OTYxMTkyNX0.L-K9YpEW3CDJIjh_qvIEQi-wZSMxvyP68T-fGXAb16k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});